blank_issues_enabled: true
contact_links:
  - name: Eu quero entrar em contato com os desenvolvedores
    url: https://olmps.co
    about: Entre em contato com o time de desenvolvimento através do site da empresa Olympus